apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anshu049/Node-App-Manifests.git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true  # Fetch changes from all directories recursively
  destination:
    server: https://kubernetes.default.svc
    namespace: nodeapp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false  # Disable validation to speed up sync
