---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: anshu049/node-test-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz  # Change this path to your application's health check endpoint
              port: 3000      # Change this port to match your container port
            initialDelaySeconds: 40
            periodSeconds: 500
            timeoutSeconds: 300
            successThreshold: 10
            failureThreshold: 30
          terminationGracePeriodSeconds: 60


---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  type: LoadBalancer  
  selector:
    app: nodeapp
  ports:
  - name: service
    protocol: TCP
    port: 80  
    targetPort: 3000
