---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: anshu049/node-test-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1000Mi"
          readinessProbe:
            httpGet:
              path: /healthz  # Change this path to your application's health check endpoint
              port: 3000      # Change this port to match your container port
            initialDelaySeconds: 4
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          terminationGracePeriodSeconds: 60


---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  type: LoadBalancer  
  selector:
    app: nodeapp
  ports:
  - name: service
    protocol: TCP
    port: 80  
    targetPort: 3000
