---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: nodeapp
    app: nodeapp
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nodeapp
      app: nodeapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: nodeapp
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: anshu049/node-test-app:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  type: LoadBalancer  
  selector:
    app: nodeapp
  ports:
  - name: service
    protocol: TCP
    port: 80  
    targetPort: 3000
