---

containers:
  - name: nodeapp
    image: anshu049/node-test-app:latest-f9010f50ec5d0aad76fa1fa0b19df30dbab43da2
    ports:
      - containerPort: 3000
    imagePullPolicy: Always  
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    readinessProbe:
      httpGet:
        path: /healthz  # Change this path to your application's health check endpoint
        port: 3000      # Change this port to match your container port
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /healthz  # Change this path to your application's health check endpoint
        port: 3000      # Change this port to match your container port
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  type: LoadBalancer  
  selector:
    app: nodeapp
  ports:
  - name: service
    protocol: TCP
    port: 80  
    targetPort: 3000
